import express, { Request, Response } from "express";
import cors from "cors";
import swaggerUi from "swagger-ui-express";
import { RegisterRoutes } from "./routes/routes";
import * as swaggerDocument from "../public/swagger.json";

const app = express();

app.use(
  cors({
    origin: process.env.FRONTEND_URL || "http://localhost:5173",
  })
);

app.use(express.json());

// Serve Swagger UI
app.use("/docs", swaggerUi.serve, swaggerUi.setup(swaggerDocument));

// Serve raw Swagger JSON (optional but useful for OpenAPI clients)
app.get("/swagger.json", (req: Request, res: Response) => {
  res.json(swaggerDocument);
});

// Register API routes generated by TSOA
RegisterRoutes(app);

// Start server
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`🚀 Server is running on http://localhost:${PORT}`);
  console.log(`📜 Swagger UI available at http://localhost:${PORT}/docs`);
});
