import "dotenv/config";
import "reflect-metadata";
import express, { Request, Response } from "express";
import cors from "cors";
import swaggerUi from "swagger-ui-express";
import { RegisterRoutes } from "./routes/routes";
import * as swaggerDocument from "../public/swagger.json";

import { errorHandler } from "./middlewares/errorhandler.middleware";
import cookieParser from "cookie-parser";
import path from "path";
import { rateLimit } from "express-rate-limit";
import "./crons/index.ts";
import { authMiddlewareWithExclusions } from "./middlewares/authExclude.middleware";
import { stripeWebHook } from "./config/stripe/routes/stripeWebhook.route";
import AppDataSource from "./config/data-source/data-source";

const app = express();

app.use(stripeWebHook);
app.use(cookieParser());

app.use(
  cors({
    origin: process.env.FRONTEND_BASE_URL || "http://localhost:5173",
    methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
    credentials: true,
    allowedHeaders: ["Content-Type", "Authorization"],
  })
);

app.use(express.json());

app.use("/docs", swaggerUi.serve, swaggerUi.setup(swaggerDocument));

// Serve static files from the public directory
app.use(express.static(path.join(__dirname, "../public")));

app.get("/swagger.json", (req: Request, res: Response) => {
  res.json(swaggerDocument);
});
app.use(authMiddlewareWithExclusions as express.RequestHandler); // Apply auth middleware with exclusions

// Serve Swagger UI

// Register API routes generated by TSOA
RegisterRoutes(app);
app.use(errorHandler);

AppDataSource.initialize()
  .then(() => {
    console.log("✅ Database connection initialized");

    app.listen(8000, () => {
      console.log(` Server is running on http://localhost:${8000}`);
      console.log(`Swagger UI available at http://localhost:${8000}/docs`);
    });
  })
  .catch((error) => {
    console.error(" Failed to initialize Data Source", error);
  });
